import type { Request, Response, NextFunction, RequestHandler } from "express";
import jwt from "jsonwebtoken";
import { createHash } from "node:crypto";
import { db, vendorApiKeysTable, oauthTokensTable, vendorsTable } from "@workspace/db";
import { eq, and, isNull, or, gt } from "drizzle-orm";

export interface ExternalUser {
  vendorId: number;
  awajimaaUserId: string;
  awajimaaUserType: "state" | "hospital" | "emergency" | "business" | "individual";
  source: string;
  jti: string;
  scopes?: string[];
}

declare global {
  namespace Express {
    interface Request {
      externalUser?: ExternalUser;
    }
  }
}

/**
 * Feature access matrix per Awajimaa user type.
 */
export const FEATURE_ACCESS: Record<string, string[]> = {
  state:      ["analytics", "campaigns", "social", "leads"],
  hospital:   ["inventory", "orders", "products", "social", "leads", "campaigns"],
  emergency:  ["inventory", "social", "leads"],
  business:   ["products", "inventory", "orders", "leads", "social", "campaigns", "analytics"],
  individual: ["social", "orders", "leads"],
};

function sha256(raw: string) { return createHash("sha256").update(raw).digest("hex"); }

/**
 * requireExternalAuth — accepts three token types:
 *
 *   1. awa_sk_*  — Vendor API key (self-generated by the vendor in Account → Developer)
 *   2. oat_*     — OAuth 2.0 access token (issued via /api/oauth/token)
 *   3. JWT       — Session token issued by /external/auth/handshake or /external/auth/mobile-handshake
 */
export const requireExternalAuth: RequestHandler = (req: Request, res: Response, next: NextFunction): void => {
  const authHeader = req.headers.authorization;
  if (!authHeader?.startsWith("Bearer ")) {
    res.status(401).json({ error: "Missing or invalid Authorization header. Use: Authorization: Bearer <token>" });
    return;
  }

  const token = authHeader.slice(7);

  if (token.startsWith("awa_sk_")) {
    // ── Vendor API key ────────────────────────────────────────────────────────
    resolveVendorApiKey(token, req, res, next);
  } else if (token.startsWith("oat_")) {
    // ── OAuth 2.0 access token ────────────────────────────────────────────────
    resolveOauthToken(token, req, res, next);
  } else {
    // ── Legacy JWT (partner / mobile-app handshake) ───────────────────────────
    resolveJwt(token, req, res, next);
  }
};

async function resolveVendorApiKey(rawKey: string, req: Request, res: Response, next: NextFunction) {
  const keyHash = sha256(rawKey);
  const now = new Date();

  const [key] = await db.select({
    id:       vendorApiKeysTable.id,
    vendorId: vendorApiKeysTable.vendorId,
    scopes:   vendorApiKeysTable.scopes,
    isActive: vendorApiKeysTable.isActive,
    revokedAt: vendorApiKeysTable.revokedAt,
    expiresAt: vendorApiKeysTable.expiresAt,
  }).from(vendorApiKeysTable)
    .where(eq(vendorApiKeysTable.keyHash, keyHash)).limit(1);

  if (!key || !key.isActive || key.revokedAt) {
    res.status(401).json({ error: "Invalid or revoked API key" });
    return;
  }
  if (key.expiresAt && key.expiresAt < now) {
    res.status(401).json({ error: "API key has expired" });
    return;
  }

  // Look up the vendor to get awajimaaUserType (or default to "business")
  const [vendor] = await db.select({
    id: vendorsTable.id,
    awajimaaUserType: vendorsTable.awajimaaUserType,
  }).from(vendorsTable).where(eq(vendorsTable.id, key.vendorId)).limit(1);

  if (!vendor) { res.status(401).json({ error: "Vendor not found" }); return; }

  // Update lastUsedAt in the background (don't await)
  db.update(vendorApiKeysTable).set({ lastUsedAt: now }).where(eq(vendorApiKeysTable.id, key.id)).catch(() => {});

  req.externalUser = {
    vendorId:         key.vendorId,
    awajimaaUserId:   `vendor_${key.vendorId}`,
    awajimaaUserType: (vendor.awajimaaUserType as ExternalUser["awajimaaUserType"]) ?? "business",
    source:           "vendor-api-key",
    jti:              `key_${key.id}`,
    scopes:           key.scopes as string[],
  };
  next();
}

async function resolveOauthToken(rawToken: string, req: Request, res: Response, next: NextFunction) {
  const tokenHash = sha256(rawToken);
  const now = new Date();

  const [token] = await db.select({
    id:       oauthTokensTable.id,
    vendorId: oauthTokensTable.vendorId,
    scopes:   oauthTokensTable.scopes,
    expiresAt: oauthTokensTable.expiresAt,
    revokedAt: oauthTokensTable.revokedAt,
    tokenType: oauthTokensTable.tokenType,
  }).from(oauthTokensTable)
    .where(and(eq(oauthTokensTable.tokenHash, tokenHash), eq(oauthTokensTable.tokenType, "access_token"))).limit(1);

  if (!token || token.revokedAt) {
    res.status(401).json({ error: "Invalid or revoked OAuth access token" });
    return;
  }
  if (token.expiresAt && token.expiresAt < now) {
    res.status(401).json({ error: "OAuth access token has expired" });
    return;
  }

  const [vendor] = await db.select({
    awajimaaUserType: vendorsTable.awajimaaUserType,
  }).from(vendorsTable).where(eq(vendorsTable.id, token.vendorId)).limit(1);

  req.externalUser = {
    vendorId:         token.vendorId,
    awajimaaUserId:   `vendor_${token.vendorId}`,
    awajimaaUserType: (vendor?.awajimaaUserType as ExternalUser["awajimaaUserType"]) ?? "business",
    source:           "oauth",
    jti:              `oat_${token.id}`,
    scopes:           token.scopes as string[],
  };
  next();
}

function resolveJwt(token: string, req: Request, res: Response, next: NextFunction) {
  const secret = process.env.SESSION_SECRET;
  if (!secret) {
    res.status(500).json({ error: "Server misconfiguration: SESSION_SECRET not set" });
    return;
  }

  try {
    const payload = jwt.verify(token, secret) as ExternalUser & { iat: number; exp: number };
    if (!["awajimaa", "mobile-app", "vendor-api-key"].includes(payload.source)) {
      res.status(401).json({ error: "Invalid token source" });
      return;
    }
    req.externalUser = {
      vendorId:         payload.vendorId,
      awajimaaUserId:   payload.awajimaaUserId,
      awajimaaUserType: payload.awajimaaUserType,
      source:           payload.source,
      jti:              payload.jti,
    };
    next();
  } catch {
    res.status(401).json({ error: "Invalid or expired token. Generate a new API key at: <your-domain>/account" });
  }
}
