/**
 * Background scheduler — polls EAS for finishing builds, then:
 *  1. Uploads the APK URL to the App Store listing
 *  2. Creates a store_apps row if one doesn't exist
 *  3. Updates vendor_mobile_apps with apkUrl, storeAppId, status: "published"
 *
 * Runs every 5 minutes.
 */

import { eq, inArray } from "drizzle-orm";
import { db, vendorMobileAppsTable, storeAppsTable, storeDeveloperAccountsTable } from "@workspace/db";
import { checkEasBuildStatus } from "./app-generator";
import { logger } from "./logger";

const INTERVAL_MS = 5 * 60 * 1000;

async function tick() {
  // Find all builds that are currently building and have an EAS build ID
  const inProgress = await db
    .select()
    .from(vendorMobileAppsTable)
    .where(eq(vendorMobileAppsTable.status, "building"));

  const withBuildId = inProgress.filter((r) => !!r.easBuildId);
  if (withBuildId.length === 0) return;

  logger.info({ count: withBuildId.length }, "[mobile-app-scheduler] Polling EAS for builds");

  for (const record of withBuildId) {
    try {
      const result = await checkEasBuildStatus(record.easBuildId!);

      if (result.status === "in_progress") continue;

      if (result.status === "failed") {
        await db
          .update(vendorMobileAppsTable)
          .set({ status: "failed", errorMessage: result.errorMessage, lastCheckedAt: new Date(), updatedAt: new Date() })
          .where(eq(vendorMobileAppsTable.id, record.id));
        logger.warn({ recordId: record.id }, "[mobile-app-scheduler] Build failed");
        continue;
      }

      // Build FINISHED — create or update the App Store listing
      const apkUrl = result.apkUrl!;

      // Find developer account for this vendor
      const vendorRow = await db.query.vendorsTable.findFirst({
        where: (v, { eq: eqFn }) => eqFn(v.id, record.vendorId),
      });
      if (!vendorRow) continue;

      const devAccount = await db.query.storeDeveloperAccountsTable.findFirst({
        where: (d, { eq: eqFn }) => eqFn(d.clerkUserId, vendorRow.clerkUserId ?? ""),
      });

      let storeAppId = record.storeAppId;

      if (!storeAppId) {
        // Auto-create App Store listing for this vendor's generated app
        const devId = devAccount?.id ?? 1; // fallback to platform developer
        const now = new Date();

        const [storeApp] = await db
          .insert(storeAppsTable)
          .values({
            developerId:       devId,
            name:              record.appName,
            slug:              record.appSlug,
            tagline:           `${record.appName} — mobile app`,
            description:       `The official ${record.appName} mobile app, generated by the Awajimaa App Builder. Access ${record.websiteUrl ?? record.repoUrl ?? "your platform"} directly from your phone.`,
            category:          "Business",
            categories:        ["Business"],
            platform:          "android",
            iconUrl:           record.iconUrl ?? "",
            screenshots:       [],
            downloadUrl:       apkUrl,
            currentVersion:    "1.0.0",
            status:            "approved",
            isFeatured:        false,
            publishingFeePaid: true,
            isPlatformApp:     false,
            packageName:       record.packageName,
            createdAt:         now,
            updatedAt:         now,
          })
          .onConflictDoUpdate({
            target: storeAppsTable.slug,
            set: { downloadUrl: apkUrl, status: "approved", updatedAt: now },
          })
          .returning({ id: storeAppsTable.id });

        storeAppId = storeApp.id;
      } else {
        // Update existing listing's download URL
        await db
          .update(storeAppsTable)
          .set({ downloadUrl: apkUrl, status: "approved", updatedAt: new Date() })
          .where(eq(storeAppsTable.id, storeAppId));
      }

      await db
        .update(vendorMobileAppsTable)
        .set({
          apkUrl,
          storeAppId,
          status:        "published",
          lastCheckedAt: new Date(),
          updatedAt:     new Date(),
        })
        .where(eq(vendorMobileAppsTable.id, record.id));

      logger.info({ recordId: record.id, apkUrl, storeAppId }, "[mobile-app-scheduler] Build published");
    } catch (err) {
      logger.error({ err, recordId: record.id }, "[mobile-app-scheduler] Error processing build");
    }
  }
}

export function startMobileAppBuildScheduler() {
  logger.info("[mobile-app-scheduler] Started — polls every 5 minutes");
  setInterval(() => void tick(), INTERVAL_MS);
  void tick(); // run once immediately
}
