-- Add a canonical public ID to every store app.
-- New apps get a structured ID generated by the API at insert time.
-- Existing rows are backfilled with a deterministic hex string derived
-- from their created_at timestamp and integer id.
ALTER TABLE store_apps ADD COLUMN IF NOT EXISTS public_id text;
CREATE UNIQUE INDEX IF NOT EXISTS store_apps_public_id_key
  ON store_apps (public_id) WHERE public_id IS NOT NULL;

-- Backfill: 12-char hex(epoch_ms) + 8-char hex(id) = 20 lowercase hex chars.
-- Format mirrors the new structured IDs closely enough for URL use.
UPDATE store_apps
SET public_id =
  lpad(to_hex(floor(extract(epoch FROM created_at) * 1000)::bigint), 12, '0') ||
  lpad(to_hex(id), 8, '0')
WHERE public_id IS NULL;
